### ISSUE TITLE
[CiviCRM 5.55.2-0 on Debian 11] CiviCRM Content will not load and display

### ISSUE THREAD

**Issue by danielfitzroyit** [bitnami/vms#565]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1a4e1a22-7e6b-e140-c905-44f5966fd9a9

### bndiagnostic output

Your instance has little available RAM memory.

### bndiagnostic was not useful. Could you please tell us why?

The resources are low because I'm running a test server - it's not causing the 404s.

### Describe your issue as much as you can

On the latest CiviCRM stacks (5.56.0-3, 5.56.0-2 and 5.55.2-0) the CiviCRM content is not loading correctly.
It is possible to login and go to the CiviCRM page, but nothing useful is displayed.
The console is full of errors - mainly 404s for the libraries directory:
GET https://ec2-54-253-174-85.ap-southeast-2.compute.amazonaws.com/libraries/civicrm/core/js/crm.ajax.js?r=ybphNen_US net::ERR_ABORTED 404 (Not Found)

I believe "libraries" should be an alias to "/opt/bitnami/drupal/vendor" - but it doesn't appear to have been set up.

I have also tested the local OVA and the same error exists.
![civi-errors](https://user-images.githubusercontent.com/35249595/209045291-691fb664-458c-4f00-b6b1-de5fe9375f43.png)

**Comment by mdhont** [comment]
Did you configure a domain for your site? It seems to be using the ec2 dynamic domain through HTTPS.

**Comment by danielfitzroyit** [comment]
No a separate domain was not configured. It was tested using IP address and the ec2 dynamic domain. Neither loaded correctly.

**Comment by danielfitzroyit** [comment]
Can confirm after further regression testing that the last working Version is 5.55.1-0 (2022-11-09)
This was the last build made with Drupal 7.

Version 5.55.1-3-r03, the first Drupal 9 version, displays the issues I have reported above (which may be as simple as a missing "libraries" alias).

**Comment by danielfitzroyit** [comment]
1) Create a free-tier EC2 on AWS Cloud e.g. t2.micro
2) Launch using the latest bitnami image from marketplace
3) Obtain the login credentials for Drupal/civicrm.
4) Connect to the machine via a web browser and login to Drupal.
5) Manually go to http://<server>/civicrm

Result: An essentially blank CiviCRM with many errors in the console.
![image](https://user-images.githubusercontent.com/35249595/211977161-d3006d1b-6b6e-431e-99dc-9f85551e5771.png)

Expected Result:
Running CiviCRM with Dashboard showing
![image](https://user-images.githubusercontent.com/35249595/211977445-efaaf6eb-5b8d-437c-81a8-9adab96a3cf6.png)

**Comment by mdhont** [comment]
I've reproduced the issue and I've created a task for fixing it. Thank you for reporting it.

**Comment by danielfitzroyit** [comment]
Any updates? We are seeing new releases and they are still broken in the same way.

**Comment by jotamartos** [comment]
Hi @danielfitzroyit, 

As @mdhont mentioned, we created a task but we can't provide you with an ETA on when it will be ready.

Thanks

**Comment by corico44** [comment]
Hello @danielfitzroyit, 

The necessary symlinks have been added to the postunpack script and the errors you encountered should no longer appear. Thank you very much for reporting this issue!

**Comment by ChrisBlueJAC** [comment]
This appears to have been marked as solved, however the latest update **bitnami-civicrm-5.58.1-0-linux-debian-11-x86_64-hvm-ebs-nami-bb60708c-08e0-4f20-af22-9fd43a8ba023** the problem persists

![Screenshot 2023-02-23 080944](https://user-images.githubusercontent.com/102330795/220771301-116a9adb-ede8-4e74-93cf-8ad0d2ff1a9b.png)

**Comment by gongomgra** [comment]
Hi @ChrisBlueJAC,

Thanks for reporting the issue. We are working on a fix for this. In the meantime, you can run the command below to workaround it

```
sudo ln -s "/opt/bitnami/drupal/vendor/civicrm/civicrm-packages" "/opt/bitnami/drupal/vendor/civicrm/packages"
```

Let us know if it worked for you.

**Comment by gongomgra** [comment]
Hi @ChrisBlueJAC,

Just a quick note to let you know that we have released a new revision of our cloud images including the fix above. You can launch the updated images from the different marketplaces or our website

https://bitnami.com/stack/civicrm

**Comment by ChrisBlueJAC** [comment]
Hi there - thanks for letting me know.
It doesn't fix the problem, without editing the $civicrm_paths in civicrm.settings.php
![image](https://user-images.githubusercontent.com/102330795/221340896-b1e428f6-0d3d-4464-a7f8-531ba3bd7522.png)
Changing that does appear to fix the issue.
![image](https://user-images.githubusercontent.com/102330795/221340610-211150a8-fc3a-4fb4-860f-86f04d1a52ac.png)

**Comment by NilsChief** [comment]
Still the same problem, spent many hours on this issue. Ugh!  Where is the file civicrm.settings.php ? I change the file to "localhost"?

**Comment by danielfitzroyit** [comment]
We updated civicrm.settings.php with the following to remove the localhost reference:
$civicrm_paths['civicrm.files']['url'] = 'http://' . $_SERVER['HTTP_HOST'] . '/sites/default/files/civicrm';

We also found a number of permissions problems:
# php not writable
sudo chmod -R 755 /bitnami/drupal/modules
sudo chmod -R 755 /bitnami/drupal/profiles
sudo chmod -R 755 /bitnami/drupal/sites
sudo chmod -R 755 /bitnami/drupal/themes
# php writable
sudo chmod -R 775 /bitnami/drupal/sites/default/files

**Comment by jotamartos** [comment]
Thank you for the information. I'll pass this information to the team so they can update the VM and release a new version.

**Comment by gongomgra** [comment]
Hi @ChrisBlueJAC, @NilsChief, @danielfitzroyit,

We released a new revision of our most recent CiviCRM solutions (version `5.59.4-1`) fixing the configuration issue in the `civicrm.settings.php` file. From now on, the `['files']['url']` field should be auto-updated with the machine IP address on first boot and on server restarts. There is also a new log entry for this action in the `/var/log/daemon.log` file. 

Can you confirm the issue is fixed in the latest image?

I launched a fresh new server using the new image and here are the results

```
bitnami@ip-172-31-45-115:~$ grep -i "updating files url.*" /var/log/daemon.log
Mar 29 08:12:39 ip-172-31-45-115 bitnami[1929]: #033[38;5;6mcivicrm #033[38;5;5m08:12:39.16 #033[0m#033[38;5;2mINFO #033[0m ==> Updating files URL in CiviCRM configuration
bitnami@ip-172-31-45-115:~$ grep "civicrm_paths.*files.*url" /opt/bitnami/drupal/sites/default/civicrm.settings.php
$civicrm_paths['civicrm.files']['url'] = 'http://44.204.183.206/sites/default/files/civicrm';
```

@danielfitzroyit, regarding the filesystem permissions, I'm afraid I can't reproduce your issue. On my server, the filesystem permissions are the expected ones. Is it possible that any action like updating Drupal, CiviCRM, or installing any plugin caused those changes on your side? If you continue having issues, please open a new ticket to avoid mixing different topics here.

```
bitnami@ip-172-31-45-115:~$ ls -larth /bitnami/drupal/
total 24K
drwxr-xr-x 6 root    root   4.0K Mar 28 21:11 ..
drwxrwxr-x 3 bitnami daemon 4.0K Mar 29 08:12 sites
drwxrwxr-x 2 bitnami daemon 4.0K Mar 29 08:12 themes
drwxrwxr-x 3 bitnami daemon 4.0K Mar 29 08:12 modules
drwxrwxr-x 2 bitnami daemon 4.0K Mar 29 08:12 profiles
drwxrwxr-x 6 daemon  root   4.0K Mar 29 08:12 .
```

**Comment by NilsChief** [comment]
Works like a charm, and fast! #thankyou! I've been watching and eyeing it, saw the update last night. I found some other errors that this fix also fixed. Kudos.

**Comment by gongomgra** [comment]
Hi @NilsChief,

Thanks for confirming the fix. We are glad it worked for you! I'm closing this ticket as solved.
